"""
Report Export Utility
Generates system health reports in TXT format.
"""

import os
from datetime import datetime

from src.services.system_info import get_full_system_info
from src.services.health_score import calculate_health_score
from src.diagnostics.network import get_network_summary


# Default output directory
REPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__)))), "reports")


def generate_txt_report(output_dir=None):
    """
    Generate a complete system health report as a text file.

    Args:
        output_dir: Directory to save the report. Defaults to project reports/ folder.

    Returns:
        dict with success status and file path.
    """
    if output_dir is None:
        output_dir = REPORTS_DIR

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Gather data
    system_info = get_full_system_info()
    health = calculate_health_score()
    network = get_network_summary()

    # Build report content
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"health_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    filepath = os.path.join(output_dir, filename)

    lines = []
    lines.append("=" * 60)
    lines.append("       PC HEALTH DIAGNOSIS REPORT")
    lines.append("=" * 60)
    lines.append(f"Generated: {timestamp}")
    lines.append("")

    # Health Score Section
    lines.append("-" * 40)
    lines.append("HEALTH SCORE")
    lines.append("-" * 40)
    lines.append(f"  Overall Score: {health['overall_score']}/100 ({health['rating']})")
    lines.append(f"  CPU Score:     {health['cpu_score']:.1f}/100")
    lines.append(f"  RAM Score:     {health['ram_score']:.1f}/100")
    lines.append(f"  Disk Score:    {health['disk_score']:.1f}/100")
    lines.append("")
    for detail in health["details"]:
        lines.append(f"  * {detail}")
    lines.append("")

    # System Information Section
    lines.append("-" * 40)
    lines.append("SYSTEM INFORMATION")
    lines.append("-" * 40)

    os_info = system_info["os"]
    lines.append(f"  OS:         {os_info['system']} {os_info['release']}")
    lines.append(f"  Version:    {os_info['version']}")
    lines.append(f"  Hostname:   {os_info['hostname']}")
    lines.append(f"  Username:   {os_info['username']}")
    lines.append(f"  Boot Time:  {system_info['boot_time']}")
    lines.append("")

    # CPU Section
    cpu_info = system_info["cpu"]
    lines.append("-" * 40)
    lines.append("CPU")
    lines.append("-" * 40)
    lines.append(f"  Processor:      {cpu_info['processor']}")
    lines.append(f"  Architecture:   {cpu_info['architecture']}")
    lines.append(f"  Physical Cores: {cpu_info['physical_cores']}")
    lines.append(f"  Logical Cores:  {cpu_info['logical_cores']}")
    lines.append(f"  Max Frequency:  {cpu_info['max_frequency']}")
    lines.append("")

    # RAM Section
    ram_info = system_info["ram"]
    lines.append("-" * 40)
    lines.append("MEMORY (RAM)")
    lines.append("-" * 40)
    lines.append(f"  Total:     {ram_info['total']}")
    lines.append(f"  Used:      {ram_info['used']}")
    lines.append(f"  Available: {ram_info['available']}")
    lines.append(f"  Usage:     {ram_info['percent_used']}%")
    lines.append("")

    # Storage Section
    lines.append("-" * 40)
    lines.append("STORAGE")
    lines.append("-" * 40)
    for disk in system_info["storage"]:
        lines.append(f"  Drive: {disk['device']}")
        lines.append(f"    Mount:      {disk['mountpoint']}")
        lines.append(f"    Filesystem: {disk['filesystem']}")
        lines.append(f"    Total:      {disk['total']}")
        lines.append(f"    Used:       {disk['used']} ({disk['percent_used']}%)")
        lines.append(f"    Free:       {disk['free']}")
        lines.append("")

    # Network Section
    lines.append("-" * 40)
    lines.append("NETWORK")
    lines.append("-" * 40)
    lines.append(f"  Status:    {'Connected' if network['connected'] else 'Disconnected'}")
    lines.append(f"  Local IP:  {network['local_ip']}")
    lines.append(f"  Hostname:  {network['hostname']}")
    lines.append("")

    # Footer
    lines.append("=" * 60)
    lines.append("  Report generated by PC Health Diagnosis Tool")
    lines.append("=" * 60)

    # Write file
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return {"success": True, "filepath": filepath, "filename": filename}
    except OSError as e:
        return {"success": False, "message": f"Failed to write report: {str(e)}"}
