"""
Generates a system health report as a .txt file.
Pulls data from the various services and formats it nicely.
"""

import os
from datetime import datetime

from src.services.system_info import get_full_system_info
from src.services.health_score import calculate_health_score
from src.diagnostics.network import get_network_summary


REPORTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "reports"
)


def generate_txt_report(output_dir=None):
    """Build and save the report. Returns path on success."""
    if output_dir is None:
        output_dir = REPORTS_DIR

    os.makedirs(output_dir, exist_ok=True)

    # gather everything
    info = get_full_system_info()
    health = calculate_health_score()
    network = get_network_summary()

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"health_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    filepath = os.path.join(output_dir, filename)

    lines = _build_report_lines(info, health, network, timestamp)

    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        return {"success": True, "filepath": filepath, "filename": filename}
    except OSError as e:
        return {"success": False, "message": f"Failed to write report: {e}"}


def _build_report_lines(info, health, network, timestamp):
    """Compose all the report sections into a list of lines."""
    lines = []

    lines.append("=" * 60)
    lines.append("       PC HEALTH DIAGNOSIS REPORT")
    lines.append("=" * 60)
    lines.append(f"Generated: {timestamp}")
    lines.append("")

    # health score
    lines.append("-" * 40)
    lines.append("HEALTH SCORE")
    lines.append("-" * 40)
    lines.append(f"  Overall: {health['overall_score']}/100 ({health['rating']})")
    lines.append(f"  CPU:     {health['cpu_score']:.1f}/100")
    lines.append(f"  RAM:     {health['ram_score']:.1f}/100")
    lines.append(f"  Disk:    {health['disk_score']:.1f}/100")
    lines.append("")
    for tip in health["details"]:
        lines.append(f"  * {tip}")
    lines.append("")

    # OS
    os_info = info["os"]
    lines.append("-" * 40)
    lines.append("SYSTEM")
    lines.append("-" * 40)
    lines.append(f"  OS:        {os_info['system']} {os_info['release']}")
    lines.append(f"  Version:   {os_info['version']}")
    lines.append(f"  Hostname:  {os_info['hostname']}")
    lines.append(f"  User:      {os_info['username']}")
    lines.append(f"  Boot time: {info['boot_time']}")
    lines.append("")

    # CPU
    cpu = info["cpu"]
    lines.append("-" * 40)
    lines.append("CPU")
    lines.append("-" * 40)
    lines.append(f"  Processor:      {cpu['processor']}")
    lines.append(f"  Arch:           {cpu['architecture']}")
    lines.append(f"  Physical cores: {cpu['physical_cores']}")
    lines.append(f"  Logical cores:  {cpu['logical_cores']}")
    lines.append(f"  Max freq:       {cpu['max_frequency']}")
    lines.append("")

    # RAM
    ram = info["ram"]
    lines.append("-" * 40)
    lines.append("MEMORY")
    lines.append("-" * 40)
    lines.append(f"  Total:     {ram['total']}")
    lines.append(f"  Used:      {ram['used']}")
    lines.append(f"  Available: {ram['available']}")
    lines.append(f"  Usage:     {ram['percent_used']}%")
    lines.append("")

    # Storage
    lines.append("-" * 40)
    lines.append("STORAGE")
    lines.append("-" * 40)
    for disk in info["storage"]:
        lines.append(f"  {disk['device']} ({disk['mountpoint']})")
        lines.append(f"    Total: {disk['total']}  Free: {disk['free']}  Used: {disk['percent_used']}%")
    lines.append("")

    # Network
    lines.append("-" * 40)
    lines.append("NETWORK")
    lines.append("-" * 40)
    lines.append(f"  Status:   {'Connected' if network['connected'] else 'Disconnected'}")
    lines.append(f"  Local IP: {network['local_ip']}")
    lines.append(f"  Hostname: {network['hostname']}")
    lines.append("")

    lines.append("=" * 60)
    lines.append("  Generated by Quantum Diagnostics v1.2")
    lines.append("=" * 60)

    return lines
